# -*- coding:utf-8 -*-
smartURL_list = ['https://smartereum.com/cryptocurrency/bitcoin/',
                 'https://smartereum.com/cryptocurrency/bitcoin-cash/',
                 'https://smartereum.com/cryptocurrency/cardano/',
                 'https://smartereum.com/cryptocurrency/dash/',
                 'https://smartereum.com/cryptocurrency/eos/',
                 'https://smartereum.com/cryptocurrency/ethereum/',
                 'https://smartereum.com/cryptocurrency/ethereum-classic-etc/',
                 'https://smartereum.com/cryptocurrency/exchanges/',
                 'https://smartereum.com/cryptocurrency/iota-miota/',
                 'https://smartereum.com/cryptocurrency/lisk-lsk/',
                 'https://smartereum.com/cryptocurrency/litecoin/',
                 'https://smartereum.com/cryptocurrency/litecoin-cash-lcc/',
                 'https://smartereum.com/cryptocurrency/monero-xmr/',
                 'https://smartereum.com/cryptocurrency/nem/',
                 'https://smartereum.com/cryptocurrency/neo/',
                 'https://smartereum.com/cryptocurrency/stellar/',
                 'https://smartereum.com/cryptocurrency/tether-usdt/',
                 'https://smartereum.com/cryptocurrency/tron-trx/',
                 'https://smartereum.com/cryptocurrency/vechain-vet/',
                 'https://smartereum.com/cryptocurrency/wallet/',
                 'https://smartereum.com/cryptocurrency/wanchain/',
                 'https://smartereum.com/cryptocurrency/xrp/']